import type { Metadata } from "../src/types/meta";

const DEV_META = {
  total: 11848,
  by_state: {
    ACT: 7,
    Alabama: 52,
    Alaska: 60,
    Argyll: 4,
    Arizona: 125,
    Arkansas: 45,
    Auckland: 44,
    Aveiro: 9,
    Açores: 1,
    "Baden-Württemberg": 195,
    "Bay of Plenty Region": 11,
    Bayern: 597,
    Beja: 1,
    Berlin: 41,
    Blekinge: 6,
    Bolzano: 4,
    "Bouche du Rhône": 3,
    Braga: 3,
    Brandenburg: 36,
    Bremen: 4,
    "British Columbia": 119,
    "Brussels Capital Region": 43,
    Busan: 9,
    Bute: 1,
    California: 919,
    "Canterbury Region": 39,
    Carlow: 1,
    "Central Finland": 2,
    "Central Ostrobothnia": 1,
    Chungcheongbukdo: 1,
    Chungcheongnamdo: 3,
    Clare: 1,
    Coimbra: 4,
    Colorado: 449,
    Connecticut: 112,
    Cork: 11,
    Daejeon: 1,
    Deagu: 1,
    Delaware: 28,
    "District of Columbia": 22,
    "Dnipropetrovsk Oblast": 1,
    Donegal: 4,
    Drenthe: 1,
    Dublin: 16,
    "East Dunbartonshire": 1,
    "East Sussex": 31,
    "Eastern Cape": 9,
    Faro: 6,
    Flanders: 2,
    Flevoland: 1,
    Florida: 312,
    "Free State": 3,
    Friesland: 1,
    Galway: 3,
    Gangwondo: 7,
    Gauteng: 17,
    Gelderland: 6,
    Georgia: 100,
    "Gisborne Region": 1,
    Groningen: 2,
    Gwangju: 1,
    Gyeonggido: 9,
    Gyeongsangbukdo: 3,
    Gyeongsangnamdo: 3,
    Halland: 4,
    Hamburg: 14,
    Hawaii: 34,
    "Hawke's Bay Region": 12,
    Hessen: 78,
    Idaho: 67,
    Illinois: 257,
    Incheon: 2,
    Indiana: 162,
    Iowa: 91,
    Jejudo: 3,
    Jeollabukdo: 3,
    Jeollanamdo: 1,
    Kainuu: 1,
    Kansas: 47,
    "Kanta-Häme": 4,
    Kentucky: 58,
    Kerry: 3,
    Kildare: 3,
    Kilkenny: 3,
    "KwaZulu-Natal": 17,
    Kymenlaakso: 2,
    Kärnten: 3,
    Laois: 2,
    Lapland: 2,
    Leiria: 1,
    Limburg: 7,
    Limerick: 2,
    Limpopo: 1,
    Lisboa: 18,
    Longford: 1,
    Louisiana: 44,
    Louth: 1,
    MIssouri: 1,
    Maine: 114,
    "Manawatū-Whanganui Region": 4,
    "Marlborough Region": 3,
    Maryland: 158,
    Massachusetts: 171,
    Mayo: 2,
    Meath: 1,
    "Mecklenburg-Vorpommern": 27,
    Michigan: 375,
    Middle: 2,
    Minnesota: 183,
    Mississippi: 17,
    Missouri: 141,
    Monaghan: 1,
    Montana: 92,
    Mpumalanga: 3,
    NSW: 144,
    NT: 3,
    Nebraska: 62,
    "Nelson Region": 7,
    Nevada: 51,
    "New Hampshire": 113,
    "New Jersey": 115,
    "New Mexico": 83,
    "New York": 419,
    Niedersachsen: 79,
    Niederösterreich: 2,
    "Noord-Brabant": 20,
    "Noord-Holland": 18,
    "Nordrhein-Westfalen": 145,
    "North Carolina": 311,
    "North Dakota": 26,
    "North Savo": 2,
    "North West": 3,
    "Northern Ostrobothnia": 3,
    Northland: 1,
    "Northland Region": 4,
    Oberösterreich: 2,
    Offaly: 2,
    Ohio: 303,
    Oklahoma: 44,
    Ontario: 164,
    Oregon: 295,
    Osaka: 10,
    Ostrobothnia: 2,
    "Otago Region": 35,
    Overijssel: 4,
    Pennsylvania: 345,
    Pirkanmaa: 6,
    Portalegre: 3,
    Porto: 18,
    "Päijät-Häme": 5,
    QLD: 81,
    "Rheinland-Pfalz": 58,
    "Rhode Island": 31,
    Roscommon: 1,
    "Région flamande": 2,
    "Région wallonne": 129,
    SA: 47,
    Saarland: 14,
    Sachsen: 67,
    "Sachsen-Anhalt": 25,
    Salzburg: 1,
    Santarém: 3,
    Satakunta: 2,
    "Schleswig-Holstein": 28,
    Seoul: 14,
    Setúbal: 2,
    Singapore: 33,
    Sligo: 2,
    "South Carolina": 79,
    "South Dakota": 45,
    "South Karelia": 1,
    "South Ostrobothnia": 4,
    "South Savo": 3,
    "Southland Region": 2,
    Steiermark: 7,
    "Stockholm County": 26,
    TAS: 26,
    "Taranaki Region": 6,
    "Tasman Region": 9,
    Tennessee: 116,
    Texas: 352,
    Thüringen: 37,
    Tipperary: 2,
    Utah: 45,
    Utrecht: 5,
    Uusimaa: 19,
    VIC: 160,
    "Varsinais-Suomi": 8,
    Vermont: 52,
    "Vila Real": 1,
    Virginia: 255,
    Viseu: 2,
    Vlaanderen: 297,
    WA: 46,
    "Waals Gewest": 2,
    "Waikato Region": 20,
    Wallonia: 3,
    Washington: 529,
    Waterford: 2,
    "Wellington Region": 43,
    "West Coast Region": 2,
    "West Dunbartonshire": 4,
    "West Sussex": 31,
    "West Virginia": 40,
    "Western Cape": 51,
    Westmeath: 1,
    Wexford: 2,
    Wicklow: 3,
    Wisconsin: 225,
    Wyoming: 52,
    Zeeland: 2,
    "Zuid-Holland": 9,
    dolnośląskie: 34,
    Åland: 1,
  },
  by_country: {
    Australia: 514,
    Austria: 15,
    Belgium: 478,
    Canada: 283,
    England: 62,
    Finland: 68,
    France: 3,
    Germany: 1445,
    Ireland: 70,
    "Isle of Man": 2,
    Italy: 4,
    Japan: 10,
    Netherlands: 76,
    "New Zealand": 243,
    Poland: 34,
    Portugal: 72,
    Scotland: 10,
    Singapore: 33,
    "South Africa": 104,
    "South Korea": 61,
    Sweden: 36,
    Ukraine: 1,
    "United States": 8224,
  },
  by_type: {
    bar: 41,
    beergarden: 3,
    brewpub: 3929,
    cidery: 7,
    closed: 642,
    contract: 210,
    large: 137,
    location: 1,
    micro: 5864,
    nano: 22,
    planning: 639,
    proprietor: 67,
    regional: 239,
    taproom: 47,
  },
  page: 1,
  per_page: 50,
};

const BrewMeta = async (): Promise<Metadata | null> => {
  if (DEV_META) {
    return DEV_META;
  }
  console.info("API: fetching meta data");
  const url = "https://api.openbrewerydb.org/v1/breweries/meta";

  try {
    const response = await fetch(url);
    if (response.ok) {
      const meta = (await response.json()) as Metadata;
      return meta;
    }
  } catch (error) {
    console.error(error);
  }
  return null;
};

export default BrewMeta;
